"""actually add player features table

Revision ID: 4b05f4bca862
Revises: a39a20a5aab3
Create Date: 2026-08-20 19:51:35.297494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b05f4bca862'
down_revision: Union[str, None] = 'a39a20a5aab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('mpg', sa.Float(), nullable=True),
    sa.Column('ppg', sa.Float(), nullable=True),
    sa.Column('apg', sa.Float(), nullable=True),
    sa.Column('rpg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_season_id')
    )
    op.create_index(op.f('ix_player_features_id'), 'player_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_features_id'), table_name='player_features')
    op.drop_table('player_features')
    # ### end Alembic commands ###
